//exports.keepers = require('./automation')
exports.FunctionsClient = require("../tasks/Functions-client")
exports.FunctionsInsurance = require("../tasks/Functions-insurance")
exports.FunctionsBilling = require("../tasks/Functions-billing")
exports.accounts = require("../tasks/accounts")
exports.balance = require("../tasks/balance")
exports.blockNumber = require("../tasks/block-number")
